import type { Metadata } from "next";

import "./globals.css";

import { cn } from "@/lib/utils";
import { urbanist } from "@/config/font";
import Footer from "@/components/footer";
import Navbar from "@/components/navbar";
import ModalProvider from "@/providers/modal-provider";
import ToastProvider from "@/providers/toast-provider";

export const metadata: Metadata = {
  title: "ecommerce-store",
  description: "Generated by appncy",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={cn(urbanist.className)}>
        <ModalProvider />
        <ToastProvider />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
